package com.iptv.player

import android.content.Context

object Language {
    private const val PREFS_KEY = "lang"

    private val it = mapOf(
        "version" to "Versione",
        "download" to "Scarica",
        "later" to "Pi\u00F9 tardi",
        "close" to "Chiudi",
        "cancel" to "Annulla",
        "save" to "Salva",
        "ok" to "OK",
        "update_title" to "Aggiornamento v",
        "update_msg" to "Scarica la nuova versione?",
        "downloading" to "Download avviato...",
        "download_fail" to "Download fallito (errore ",
        "dm_unavailable" to "DownloadManager non disponibile",
        "settings" to "Impostazioni",
        "diagnostics" to "Diagnostica",
        "donate" to "\u26A1 Fai una donazione",
        "donate_title" to "Donazione Bitcoin",
        "donate_msg" to "Supporta lo sviluppo inviando BTC:",
        "donate_copy" to "Copia indirizzo",
        "backup" to "Backup Playlist",
        "restore" to "Ripristina",
        "cloud_clear" to "Cancella dati Cloud",
        "proxy_search" to "Cerca Proxy Veloci",
        "proxy_searching" to "Ricerca...",
        "proxy_none" to "Nessuno trovato",
        "proxy_not_tested" to "Non testato",
        "proxy_all" to "Tutti i paesi",
        "proxy_country" to "Paese proxy",
        "filter_live" to "LIVE TV",
        "filter_movies" to "FILM",
        "filter_series" to "SERIE TV",
        "search_hint" to "Cerca canale...",
        "no_channels" to "Nessun canale trovato",
        "no_playlist" to "Nessuna playlist",
        "add_playlist" to "Aggiungi Playlist",
        "add_cloud" to "Carica Playlist da Cloud",
        "cloud_checking" to "Verifica cloud in corso...",
        "theme_title" to "Seleziona Tema",
        "playlist_loading" to "Caricamento canali...",
        "epg_downloading" to "EPG: scaricamento...",
        "epg_parsing" to "EPG: parsing...",
        "epg_linking" to "EPG: associando...",
        "epg_no_match" to "EPG: 0 match - nomi canali diversi?",
        "epg_fail" to "EPG: download fallito",
        "saved" to "Salvato",
        "copied" to "Link copiato!",
        "btc_copied" to "Indirizzo copiato!",
        "cloud_deleted" to "Cloud cancellato",
        "backup_ok" to "Backup salvato!",
        "backup_fail" to "Backup fallito",
        "restore_ok" to "playlist ripristinate!",
        "restore_fail" to "Nessun backup",
        "exit_msg" to "Premi di nuovo INDIETRO per uscire",
        "guide_title" to "Guida",
        "guide_intro" to "Player per playlist IPTV, M3U, Xtream Codes e Stalker MAC.",
        "guide_add" to "Aggiungere una Playlist",
        "guide_add_body" to "Premi il pulsante + in alto a destra. Puoi inserire:<br>\u2022 M3U URL: incolla il link della playlist<br>\u2022 Xtream Codes: Server + Username + Password<br>\u2022 Stalker MAC: Server + MAC address<br><br>Oppure vai su gbclient.github.io/iptv-client da PC/smartphone, inserisci il codice ID e clicca Invia.<br>Poi sull'app premi + \u2192 Carica Playlist da Cloud per scaricarla.",
        "guide_switch" to "Cambiare Playlist",
        "guide_switch_body" to "Tocca il codice ID in alto. Se hai pi\u00F9 playlist, si apre la lista per selezionarle.<br>Tieni premuto su una playlist per eliminarla.",
        "guide_search" to "Ricerca Canali",
        "guide_search_body" to "Premi \uD83D\uDD0D e digita il nome del canale. La ricerca filtra in tempo reale.",
        "guide_filters" to "Filtri LIVE / VOD / Serie",
        "guide_filters_body" to "Sotto l'ID ci sono i filtri: LIVE TV, FILM e SERIE TV. Toccali per vedere solo quel tipo.<br>Tieni premuto per rimuovere il filtro.",
        "guide_fav" to "Preferiti e Cronologia",
        "guide_fav_body" to "Tieni premuto su un canale per aggiungerlo/rimuoverlo dai Preferiti.<br>I canali visti appaiono in Cronologia.<br>Entrambi sono nella lista categorie in alto.",
        "guide_theme" to "Tema",
        "guide_theme_body" to "Premi \uD83C\uDFA8 per cambiare il colore dell'interfaccia tra Rosso, Blu, Verde, Viola e Arancio.",
        "guide_epg" to "EPG (Guida TV)",
        "guide_epg_body" to "Se la playlist contiene un EPG, viene scaricato automaticamente.<br>Puoi impostare un EPG personalizzato nelle Impostazioni.",
        "guide_proxy" to "Proxy",
        "guide_proxy_body" to "Proxy Stalker: carica un portale Stalker e premi PRX per condividerlo con altri via Firebase, senza VPS.<br><br>Proxy automatico: nelle Impostazioni puoi attivare il proxy gratuito per aggirare blocchi ISP, forzarlo sullo streaming o cercare proxy veloci manualmente.",
        "guide_cloud" to "Cloud",
        "guide_cloud_body" to "Le tue playlist vengono salvate automaticamente sul cloud (Firebase).<br>Da un altro dispositivo puoi inviare una playlist usando lo stesso codice ID.",
        "guide_updates" to "Aggiornamenti",
        "guide_updates_body" to "L'app controlla automaticamente la presenza di nuove versioni all'avvio.<br>Se trovi un aggiornamento, premi Scarica per installarlo.",
        "guide_disclaimer" to "Disclaimer",
        "guide_disclaimer_body" to "IPTV Player \u00E8 un player video. Non ospita, non trasmette e non distribuisce alcun contenuto protetto da copyright.\nL'utente \u00E8 l'unico responsabile dei contenuti riprodotti tramite le playlist inserite.\nQuesto software viene fornito \"cos\u00EC com'\u00E8\", senza garanzia di alcun tipo.",
        "proxy_activate" to "Proxy attivo! Condividi il codice con gli altri.",
        "proxy_deactivate" to "Proxy disattivato",
        "proxy_no_stalker" to "Non ci sono proxy attivi.\nPer diventare provider:\n1. Aggiungi portale Stalker (+ \u2192 Stalker MAC)\n2. Carica canali\n3. Premi PRX",
        "proxy_guide" to "Proxy Stalker consente a un dispositivo con abbonamento Stalker di condividere i canali con altri utenti via Firebase, senza server VPS.<br><br>Per attivare: carica un portale Stalker e premi PRX. Gli altri ti vedranno nella lista playlist.",
        "lang_it" to "ITA",
        "lang_en" to "ENG",
        "lang_de" to "DE"
    )

    private val en = mapOf(
        "version" to "Version",
        "download" to "Download",
        "later" to "Later",
        "close" to "Close",
        "cancel" to "Cancel",
        "save" to "Save",
        "ok" to "OK",
        "update_title" to "Update v",
        "update_msg" to "Download the new version?",
        "downloading" to "Download started...",
        "download_fail" to "Download failed (error ",
        "dm_unavailable" to "DownloadManager unavailable",
        "settings" to "Settings",
        "diagnostics" to "Diagnostics",
        "donate" to "\u26A1 Make a Donation",
        "donate_title" to "Bitcoin Donation",
        "donate_msg" to "Support development by sending BTC:",
        "donate_copy" to "Copy address",
        "backup" to "Backup Playlists",
        "restore" to "Restore",
        "cloud_clear" to "Clear Cloud Data",
        "proxy_search" to "Find Fast Proxies",
        "proxy_searching" to "Searching...",
        "proxy_none" to "None found",
        "proxy_not_tested" to "Not tested",
        "proxy_all" to "All countries",
        "proxy_country" to "Proxy country",
        "filter_live" to "LIVE TV",
        "filter_movies" to "MOVIES",
        "filter_series" to "SERIES",
        "search_hint" to "Search channel...",
        "no_channels" to "No channels found",
        "no_playlist" to "No playlist",
        "add_playlist" to "Add Playlist",
        "add_cloud" to "Load Playlist from Cloud",
        "cloud_checking" to "Checking cloud...",
        "theme_title" to "Select Theme",
        "playlist_loading" to "Loading channels...",
        "epg_downloading" to "EPG: downloading...",
        "epg_parsing" to "EPG: parsing...",
        "epg_linking" to "EPG: linking...",
        "epg_no_match" to "EPG: 0 match - different channel names?",
        "epg_fail" to "EPG: download failed",
        "saved" to "Saved",
        "copied" to "Link copied!",
        "btc_copied" to "Address copied!",
        "cloud_deleted" to "Cloud deleted",
        "backup_ok" to "Backup saved!",
        "backup_fail" to "Backup failed",
        "restore_ok" to "playlists restored!",
        "restore_fail" to "No backup found",
        "exit_msg" to "Press BACK again to exit",
        "guide_title" to "Guide",
        "guide_intro" to "Player for IPTV, M3U, Xtream Codes and Stalker MAC playlists.",
        "guide_add" to "Adding a Playlist",
        "guide_add_body" to "Press the + button on the top right. You can enter:<br>\u2022 M3U URL: paste the playlist link<br>\u2022 Xtream Codes: Server + Username + Password<br>\u2022 Stalker MAC: Server + MAC address<br><br>Or go to gbclient.github.io/iptv-client from your PC/smartphone, enter the ID code and click Send.<br>Then on the app press + \u2192 Load Playlist from Cloud to download it.",
        "guide_switch" to "Switching Playlists",
        "guide_switch_body" to "Tap the ID code at the top. If you have multiple playlists, the list opens so you can select one.<br>Long press a playlist to delete it.",
        "guide_search" to "Search Channels",
        "guide_search_body" to "Press \uD83D\uDD0D and type the channel name. The search filters in real time.",
        "guide_filters" to "LIVE / VOD / Series Filters",
        "guide_filters_body" to "Below the ID there are filters: LIVE TV, MOVIES and SERIES. Tap to view only that type.<br>Long press to remove the filter.",
        "guide_fav" to "Favorites & History",
        "guide_fav_body" to "Long press a channel to add/remove it from Favorites.<br>Watched channels appear in History.<br>Both are in the category list at the top.",
        "guide_theme" to "Theme",
        "guide_theme_body" to "Press \uD83C\uDFA8 to change the interface color: Red, Blue, Green, Purple or Orange.",
        "guide_epg" to "EPG (TV Guide)",
        "guide_epg_body" to "If the playlist contains an EPG, it is downloaded automatically.<br>You can set a custom EPG in Settings.",
        "guide_proxy" to "Proxy",
        "guide_proxy_body" to "Stalker Proxy: load a Stalker portal and press PRX to share channels with others via Firebase, no VPS needed.<br><br>Auto Proxy: in Settings you can enable the free proxy to bypass ISP blocks, force it on streaming, or search for fast proxies manually.",
        "guide_cloud" to "Cloud",
        "guide_cloud_body" to "Your playlists are automatically saved to the cloud (Firebase).<br>From another device you can send a playlist using the same ID code.",
        "guide_updates" to "Updates",
        "guide_updates_body" to "The app automatically checks for new versions on startup.<br>If an update is found, press Download to install it.",
        "guide_disclaimer" to "Disclaimer",
        "guide_disclaimer_body" to "IPTV Player is a video player. It does not host, transmit or distribute any copyrighted content.\nThe user is solely responsible for the content played through the playlists entered.\nThis software is provided \"as is\", without any warranty.",
        "proxy_activate" to "Proxy active! Share the code with others.",
        "proxy_deactivate" to "Proxy deactivated",
        "proxy_no_stalker" to "No active proxies.\nTo become a provider:\n1. Add Stalker portal (+ \u2192 Stalker MAC)\n2. Load channels\n3. Press PRX",
        "proxy_guide" to "Stalker Proxy lets one device with a Stalker subscription share channels with other users via Firebase, no VPS needed.<br><br>To activate: load a Stalker portal and press PRX. Others will see you in the playlist list.",
        "lang_it" to "ITA",
        "lang_en" to "ENG",
        "lang_de" to "DE"
    )

    private val de = mapOf(
        "version" to "Version",
        "download" to "Herunterladen",
        "later" to "Sp\u00E4ter",
        "close" to "Schlie\u00DFen",
        "cancel" to "Abbrechen",
        "save" to "Speichern",
        "ok" to "OK",
        "update_title" to "Update v",
        "update_msg" to "Neue Version herunterladen?",
        "downloading" to "Download gestartet...",
        "download_fail" to "Download fehlgeschlagen (Fehler ",
        "dm_unavailable" to "DownloadManager nicht verf\u00FCgbar",
        "settings" to "Einstellungen",
        "diagnostics" to "Diagnose",
        "donate" to "\u26A1 Spenden",
        "donate_title" to "Bitcoin Spende",
        "donate_msg" to "Unterst\u00FCtze die Entwicklung mit BTC:",
        "donate_copy" to "Adresse kopieren",
        "backup" to "Playlist sichern",
        "restore" to "Wiederherstellen",
        "cloud_clear" to "Cloud-Daten l\u00F6schen",
        "proxy_search" to "Schnelle Proxys suchen",
        "proxy_searching" to "Suche...",
        "proxy_none" to "Keine gefunden",
        "proxy_not_tested" to "Nicht getestet",
        "proxy_all" to "Alle L\u00E4nder",
        "proxy_country" to "Proxy-Land",
        "filter_live" to "LIVE TV",
        "filter_movies" to "FILME",
        "filter_series" to "SERIEN",
        "search_hint" to "Sender suchen...",
        "no_channels" to "Keine Sender gefunden",
        "no_playlist" to "Keine Playlist",
        "add_playlist" to "Playlist hinzuf\u00FCgen",
        "add_cloud" to "Playlist aus Cloud laden",
        "cloud_checking" to "Cloud-Pr\u00FCfung...",
        "theme_title" to "Thema ausw\u00E4hlen",
        "playlist_loading" to "Sender werden geladen...",
        "epg_downloading" to "EPG: Download...",
        "epg_parsing" to "EPG: Verarbeitung...",
        "epg_linking" to "EPG: Verkn\u00FCpfung...",
        "epg_no_match" to "EPG: 0 Treffer - andere Sendernamen?",
        "epg_fail" to "EPG: Download fehlgeschlagen",
        "saved" to "Gespeichert",
        "copied" to "Link kopiert!",
        "btc_copied" to "Adresse kopiert!",
        "cloud_deleted" to "Cloud gel\u00F6scht",
        "backup_ok" to "Backup gespeichert!",
        "backup_fail" to "Backup fehlgeschlagen",
        "restore_ok" to "Playlists wiederhergestellt!",
        "restore_fail" to "Kein Backup gefunden",
        "exit_msg" to "Erneut ZUR\u00DCK dr\u00FCcken zum Beenden",
        "guide_title" to "Anleitung",
        "guide_intro" to "Player f\u00FCr IPTV, M3U, Xtream Codes und Stalker MAC Playlists.",
        "guide_add" to "Playlist hinzuf\u00FCgen",
        "guide_add_body" to "Dr\u00FCcke die + Taste oben rechts. Du kannst eingeben:<br>\u2022 M3U URL: Playlist-Link einf\u00FCgen<br>\u2022 Xtream Codes: Server + Benutzername + Passwort<br>\u2022 Stalker MAC: Server + MAC-Adresse<br><br>Oder gehe auf gbclient.github.io/iptv-client vom PC/Smartphone, gib den ID-Code ein und klicke Senden.<br>Dann in der App + \u2192 Playlist aus Cloud laden dr\u00FCcken.",
        "guide_switch" to "Playlist wechseln",
        "guide_switch_body" to "Tippe auf den ID-Code oben. Bei mehreren Playlists \u00F6ffnet sich die Liste zur Auswahl.<br>Lang dr\u00FCcken, um eine Playlist zu l\u00F6schen.",
        "guide_search" to "Sender suchen",
        "guide_search_body" to "Dr\u00FCcke \uD83D\uDD0D und gib den Sendernamen ein. Die Suche filtert in Echtzeit.",
        "guide_filters" to "LIVE / VOD / Serien Filter",
        "guide_filters_body" to "Unter der ID befinden sich Filter: LIVE TV, FILME und SERIEN. Tippe, um nur diesen Typ anzuzeigen.<br>Lang dr\u00FCcken, um den Filter zu entfernen.",
        "guide_fav" to "Favoriten & Verlauf",
        "guide_fav_body" to "Lang auf einen Sender dr\u00FCcken, um ihn zu Favoriten hinzuzuf\u00FCgen/entfernen.<br>Angesehene Sender erscheinen im Verlauf.<br>Beide sind in der Kategorieliste oben.",
        "guide_theme" to "Thema",
        "guide_theme_body" to "Dr\u00FCcke \uD83C\uDFA8, um die Farbe der Oberfl\u00E4che zu \u00E4ndern: Rot, Blau, Gr\u00FCn, Violett oder Orange.",
        "guide_epg" to "EPG (TV-Programm)",
        "guide_epg_body" to "Wenn die Playlist einen EPG enth\u00E4lt, wird er automatisch heruntergeladen.<br>Du kannst einen eigenen EPG in den Einstellungen festlegen.",
        "guide_proxy" to "Proxy",
        "guide_proxy_body" to "Stalker Proxy: Lade ein Stalker-Portal und dr\u00FCcke PRX, um Kan\u00E4le \u00FCber Firebase mit anderen zu teilen, ohne VPS.<br><br>Auto-Proxy: In den Einstellungen kannst du den kostenlosen Proxy aktivieren, um ISP-Sperren zu umgehen, ihn f\u00FCr Streaming erzwingen oder schnelle Proxys suchen.",
        "guide_cloud" to "Cloud",
        "guide_cloud_body" to "Deine Playlists werden automatisch in der Cloud (Firebase) gespeichert.<br>Von einem anderen Ger\u00E4t kannst du eine Playlist mit demselben ID-Code senden.",
        "guide_updates" to "Updates",
        "guide_updates_body" to "Die App pr\u00FCft beim Start automatisch nach neuen Versionen.<br>Wenn ein Update gefunden wird, dr\u00FCcke Herunterladen, um es zu installieren.",
        "guide_disclaimer" to "Haftungsausschluss",
        "guide_disclaimer_body" to "IPTV Player ist ein Videoplayer. Er hostet, \u00FCbertr\u00E4gt oder verteilt keine urheberrechtlich gesch\u00FCtzten Inhalte.\nDer Benutzer ist allein verantwortlich f\u00FCr die Inhalte, die \u00FCber die eingegebenen Playlists abgespielt werden.\nDiese Software wird \"wie besehen\" ohne jegliche Gew\u00E4hrleistung bereitgestellt.",
        "proxy_activate" to "Proxy aktiv! Teile den Code mit anderen.",
        "proxy_deactivate" to "Proxy deaktiviert",
        "proxy_no_stalker" to "Keine aktiven Proxys.\nUm ein Provider zu werden:\n1. Stalker-Portal hinzuf\u00FCgen (+ \u2192 Stalker MAC)\n2. Sender laden\n3. PRX dr\u00FCcken",
        "lang_it" to "ITA",
        "lang_en" to "ENG",
        "lang_de" to "DE"
    )

    private val maps = mapOf("it" to it, "en" to en, "de" to de)

    fun get(ctx: Context): String {
        return ctx.getSharedPreferences("iptv_prefs", Context.MODE_PRIVATE).getString(PREFS_KEY, "it") ?: "it"
    }

    fun set(ctx: Context, lang: String) {
        ctx.getSharedPreferences("iptv_prefs", Context.MODE_PRIVATE).edit().putString(PREFS_KEY, lang).apply()
    }

    fun t(ctx: Context, key: String): String {
        val lang = get(ctx)
        return maps[lang]?.get(key) ?: it[key] ?: key
    }
}
